#!/usr/bin/python3
################################################################################
#                                   PhononTools                                #
# Author: Harrison LaBollita                                                   #
################################################################################
import os
import sys
import numpy as np
import yaml
import matplotlib.pyplot as plt

from phononTools.base.parse import parse 
from phononTools.base.mesh import mesh
from phononTools.base.irreps import irreps
from phononTools.base.plot import plot
from phononTools.base.dos import dos
from phononTools.base.band_dos import band_dos

def main():

    args = parse()

    if args.mesh_file != None:
        pFreq, pVecs = mesh(args.mesh_file, args.qpoint, args.units)
    else:
        pFreq = None
        pVecs = None

    if args.irreps_file != None:
        pFreqTable = irreps(args.irreps_file, args.units)
    else:
        pFreqTable = None

    if args.band_file != None and args.dos != None:
        band_dos(args)

    elif args.band_file != None and args.dos == None:
        plot(args)

    elif args.band_file == None and args.dos != None:
        dos(args)

    if args.band_file == None and pFreq == None and pVecs == None and pFreqTable == None:
        print("PhononTools requires at least one yaml file. For more information, try python phononTools.py -h")
    return pFreq, pVecs, pFreqTable

if __name__ == "__main__":
    pFreq, pVecs, pFreqTable = main()
